/*
 * This file is generated by jOOQ.
 */
package org.spotiman.db.jooq.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.spotiman.db.jooq.Public;
import org.spotiman.db.jooq.tables.records.TracksRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tracks extends TableImpl<TracksRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.tracks</code>
     */
    public static final Tracks TRACKS = new Tracks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TracksRecord> getRecordType() {
        return TracksRecord.class;
    }

    /**
     * The column <code>public.tracks.id</code>.
     */
    public final TableField<TracksRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.tracks.album_id</code>.
     */
    public final TableField<TracksRecord, String> ALBUM_ID = createField(DSL.name("album_id"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.tracks.bpm</code>.
     */
    public final TableField<TracksRecord, Integer> BPM = createField(DSL.name("bpm"), SQLDataType.INTEGER, this, "");

    private Tracks(Name alias, Table<TracksRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Tracks(Name alias, Table<TracksRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.tracks</code> table reference
     */
    public Tracks(String alias) {
        this(DSL.name(alias), TRACKS);
    }

    /**
     * Create an aliased <code>public.tracks</code> table reference
     */
    public Tracks(Name alias) {
        this(alias, TRACKS);
    }

    /**
     * Create a <code>public.tracks</code> table reference
     */
    public Tracks() {
        this(DSL.name("tracks"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Tracks as(String alias) {
        return new Tracks(DSL.name(alias), this);
    }

    @Override
    public Tracks as(Name alias) {
        return new Tracks(alias, this);
    }

    @Override
    public Tracks as(Table<?> alias) {
        return new Tracks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Tracks rename(String name) {
        return new Tracks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tracks rename(Name name) {
        return new Tracks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Tracks rename(Table<?> name) {
        return new Tracks(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tracks where(Condition condition) {
        return new Tracks(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tracks where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tracks where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tracks where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tracks where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tracks where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tracks where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Tracks where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tracks whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Tracks whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
