/*
 * This file is generated by jOOQ.
 */
package org.spotiman.db.jooq;


import org.spotiman.db.jooq.tables.FlywaySchemaHistory;
import org.spotiman.db.jooq.tables.Tracks;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.tracks</code>.
     */
    public static final Tracks TRACKS = Tracks.TRACKS;
}
